package test05_user_exception;

public class UserTest1 extends Exception{
	
	UserTest1(){
		System.out.println("나만의 예외가 발생했습니다.");
	}

}
